# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZXxnbPbdnWx0hi0oHs5r98GXrDfzx1c
"""

import streamlit as st
import pandas as pd
import joblib

# ===============================
# Load trained artifacts
# ===============================
model = joblib.load("model.pkl")
owner_encoder = joblib.load("owner_encoder.pkl")
feature_columns = joblib.load("feature_columns.pkl")

st.title("Car Price Prediction")

# ===============================
# User Inputs
# ===============================
owner = st.selectbox(
    "Owner Type",
    [
        'First Owner',
        'Second Owner',
        'Third Owner',
        'Fourth & Above Owner',
        'Test Drive Car'
    ]
)

fuel = st.selectbox("Fuel Type", ['Petrol', 'Diesel', 'CNG'])
seller_type = st.selectbox("Seller Type", ['Individual', 'Dealer'])
transmission = st.selectbox("Transmission", ['Manual', 'Automatic'])

km_driven = st.number_input("KM Driven", min_value=0)
seats = st.number_input("Seats", min_value=2, max_value=10)
yeard_old = st.number_input("Car Age (Years)", min_value=0)
mileage_value = st.number_input("Mileage")
engine_value = st.number_input("Engine CC")
max_power_value = st.number_input("Max Power")

# ===============================
# Create input DataFrame
# ===============================
input_df = pd.DataFrame([{
    'owner': owner,
    'fuel': fuel,
    'seller_type': seller_type,
    'transmission': transmission
}])

# ===============================
# Apply encodings (NO fit)
# ===============================
input_df['owner'] = owner_encoder.transform(input_df[['owner']])

input_df = pd.get_dummies(input_df)

# ===============================
# Add missing columns
# ===============================
for col in feature_columns:
    if col not in input_df.columns:
        input_df[col] = 0

# ===============================
# Keep correct column order
# ===============================
input_df = input_df[feature_columns]

# ===============================
# Prediction
# ===============================
if st.button("Predict Price"):
    prediction = model.predict(input_df)
    st.success(f"💰 Estimated Price: ₹ {prediction[0]:,.2f}")
